pipelines:
  firstpipeline:
    group: firstGroup
    materials:
      anyrepo:
        git: https://github.com/voodoomsr/myfirstpipeline
    stages:
      - stage1:
          jobs:
            jobs1:
              tasks:
                - exec:
                    command: ./build
                - exec:
                    command: docker
                    arguments:
                      - build
                      - -t
                      - my-php-app
                      - .
                - exec:
                    command: docker
                    arguments:
                      - run
                      - my-php-app
